<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BFD7TB1" failures="2" tests="12" name="com.ictwebsite.test.EventsTestClass" time="430.081" errors="0" timestamp="2024-01-08T10:22:11 IST" skipped="0">
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase6" time="38.381"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase5" time="32.053">
    <failure message="expected:&lt;Registration Successfull&gt; but was:&lt;Registration Unsuccessful due to wrong credentials&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<Registration Successfull> but was:<Registration Unsuccessful due to wrong credentials>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at com.ictwebsite.test.EventsTestClass.testcase5(EventsTestClass.java:87)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testcase5 -->
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase10" time="32.242"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase2" time="32.960"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase12" time="32.658"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase1" time="7.725"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase4" time="31.043"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase3" time="35.163"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase9" time="30.743"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase7" time="31.592">
    <failure message="expected:&lt;Registration Successfull&gt; but was:&lt;Registration Unsuccessful due to wrong credentials&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected:<Registration Successfull> but was:<Registration Unsuccessful due to wrong credentials>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at com.ictwebsite.test.EventsTestClass.testcase7(EventsTestClass.java:111)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testcase7 -->
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase11" time="32.627"/>
  <testcase classname="com.ictwebsite.test.EventsTestClass" name="testcase8" time="92.894"/>
</testsuite> <!-- com.ictwebsite.test.EventsTestClass -->
